services:
  backend:
    container_name: team2-back-app-pipeline
    build:
      context: .
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    networks:
      - team2-network

networks:
  team2-network:
    external: true
