name: CI Pipeline

on:
  pull_request:
    branches:
        - main
  push:
    branches: 
        - "**"

jobs:
    code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node and Dependencies
          uses: ./.github/actions/setup

        - name: Run Biome Linting
          run: npm run lint

        - name: Run Biome Formatting Check
          run: npm run format:check

    test:
        needs: code-quality
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node and Dependencies
          uses: ./.github/actions/setup

        - name: Generate Prisma Client
          run: DATABASE_URL="postgresql://dummy:dummy@localhost/dummy" npx prisma generate

        - name: Run Tests with Coverage
          env:
            DATABASE_URL: "postgresql://dummy:dummy@localhost/dummy"
            JWT_SECRET: "test-secret-key-for-ci-testing-minimum-32-chars"
            JWT_EXPIRES_IN: "24h"
          run: npm run test:coverage
    
    build:
        needs: test
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node and Dependencies
          uses: ./.github/actions/setup
        
        - name: Generate Prisma Client
          run: DATABASE_URL="postgresql://dummy:dummy@localhost/dummy" npx prisma generate

        - name: Build Application
          run: npm run build

    containerise:
          needs: build
          runs-on: ubuntu-latest
          steps:
          - name: Checkout code
            uses: actions/checkout@v4
          - name: Setup Node and Dependencies
            uses: ./.github/actions/setup
          - name: Generate Prisma Client
            run: DATABASE_URL="postgresql://dummy:dummy@localhost/dummy" npx prisma generate
          - name: Build Docker Image
            run: |
                docker build -t team2-lauren-backend:latest .
          - name: Tag Docker Image
            run: |
                docker tag team2-lauren-backend:latest ${{ secrets.ACR_LOGIN_SERVER }}/team2-lauren-backend:latest
                docker tag team2-lauren-backend:latest ${{ secrets.ACR_LOGIN_SERVER }}/team2-lauren-backend:${{ github.sha }}
          - name: Log in to Azure Container Registry
            if: github.ref == 'refs/heads/main' && github.event_name == 'push'
            uses: azure/docker-login@v1
            with:
              login-server: ${{ secrets.ACR_LOGIN_SERVER }}
              username: ${{ secrets.ACR_USERNAME }}
              password: ${{ secrets.ACR_PASSWORD }}
          - name: Push Docker Image to Azure Container Registry
            if: github.ref == 'refs/heads/main' && github.event_name == 'push'
            run: |
                docker push ${{ secrets.ACR_LOGIN_SERVER }}/team2-lauren-backend:latest
                docker push ${{ secrets.ACR_LOGIN_SERVER }}/team2-lauren-backend:${{ github.sha }}