name: CI Pipeline

on:
  pull_request:
    branches:
        - main
  push:
    branches: 
        - "**"

jobs:
    code-quality:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node and Dependencies
          uses: ./.github/actions/setup

        - name: Run Biome Linting
          run: npm run lint

        - name: Run Biome Formatting Check
          run: npm run format:check

    test:
        needs: code-quality
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node and Dependencies
          uses: ./.github/actions/setup

        - name: Generate Prisma Client
          run: DATABASE_URL="postgresql://dummy:dummy@localhost/dummy" npx prisma generate

        - name: Run Tests with Coverage
          env:
            DATABASE_URL: "postgresql://dummy:dummy@localhost/dummy"
            JWT_SECRET: "test-secret-key-for-ci-testing-minimum-32-chars"
            JWT_EXPIRES_IN: "24h"
          run: npm run test:coverage
    
    build:
        needs: test
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Node and Dependencies
          uses: ./.github/actions/setup
        
        - name: Generate Prisma Client
          run: DATABASE_URL="postgresql://dummy:dummy@localhost/dummy" npx prisma generate

        - name: Build Application
          run: npm run build

    Containerise:
        needs: build
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Login to Azure Container Registry
          uses: azure/docker-login@v1
          with:
            login-server: ${{ secrets.ACR_LOGIN_SERVER }}
            username: ${{ secrets.ACR_USERNAME }}
            password: ${{ secrets.ACR_PASSWORD }}

        - name: Build Docker Image
          run: |
            docker build --build-arg DATABASE_URL="postgresql://sam@localhost:5432/postgres?schema=job_roles_db" -t team2-back-app-pipeline:latest .

        - name: Tag Docker Image
          run: |
            docker tag team2-back-app-pipeline:latest ${{ secrets.ACR_LOGIN_SERVER }}/team2-back-app-pipeline:latest
            docker tag team2-back-app-pipeline:latest ${{ secrets.ACR_LOGIN_SERVER }}/team2-back-app-pipeline:${{ github.sha }}

        - name: Push Docker Image
          run: |
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/team2-back-app-pipeline:latest
            docker push ${{ secrets.ACR_LOGIN_SERVER }}/team2-back-app-pipeline:${{ github.sha }}   


    Terraform-Plan:
        needs: Containerise
        runs-on: ubuntu-latest
        env:
          ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
          ARM_ACCESS_KEY: ${{ secrets.ARM_ACCESS_KEY }}
        steps:
          - uses: actions/checkout@v3
          - uses: hashicorp/setup-terraform@v2
          - run: terraform init
          - run: terraform plan

    Terraform-Apply:
        needs: Terraform-Plan
        runs-on: ubuntu-latest
        
        steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.5.0

        #- name: Terraform Apply
        #  run: terraform apply -auto-approve tfplan